### ISSUE TITLE
AMQP appender brings down IIS W3WP.exe

### ISSUE THREAD

**Issue by scottEdwardsAllanGray** [jjchiw/gelf4net#33]
If you configure the AMQP appender incorrectly (e.g. change <remoteAddress value="my.local.exchange" /> to a non-existent host like <remoteAddress value="**xxx.**my.local.exchange" />, the appender throws an exception that brings down W3WP.exe. 

This happens here in GelfAmqpAppender.cs:
protected override void OnClose()
        {
            Channel.Close();
            Channel.Dispose();
            Connection.Close();
            Connection.Dispose();
        }

If you change this code as follows, the problem goes away:
protected override void OnClose()
        {
            if (Channel != null)
            {
                Channel.Close();
                Channel.Dispose();
            }
            if (Connection != null)
            {
                Connection.Close();
                Connection.Dispose();
            }
        }

So, either Channel or Connection are null (not sure which).

Stack traces from the Windows application log, in order, are as follows:
[001.txt](https://github.com/jjchiw/gelf4net/files/147917/001.txt)
[002.txt](https://github.com/jjchiw/gelf4net/files/147918/002.txt)
[003.txt](https://github.com/jjchiw/gelf4net/files/147919/003.txt)

**Comment by jjchiw** [comment]
Thanks! I merged the changes of the PR #34

**Comment by scottEdwardsAllanGray** [comment]
Superb! Thank you.

**Comment by jjchiw** [comment]
:)
