### ISSUE TITLE
The licensing presented on github doesn't match the license presented in nuget

### ISSUE THREAD

**Issue by garrmark** [jjchiw/gelf4net#40]
the nuget package points to the Apache license http://www.apache.org/licenses/LICENSE-2.0.html

github https://github.com/jjchiw/gelf4net states "This project is licensed under the MIT license"

Is one of those the correct license?

**Comment by jjchiw** [comment]
Didn't see that....

I think we will keep the MIT license. I'll update the nuget package

Thanks

**Comment by jjchiw** [comment]
Ok, it took my time, to update the license package  but it's done. Yay! :)
