### ISSUE TITLE
could not create appender 

### ISSUE THREAD

**Issue by raynaldgirard** [jjchiw/gelf4net#55]
Hello,

I'm using the GelfAmqpAppender but I **do not want** my messages to be GZip before being sent to RabbitMQ.

I changed the GzipMessage function to remove the GZip. To recomile without error and I replace the DLL Gelf4Net.dll in my solution by my version.

Now, I have this error message "**could not create appender**".

log4net:ERROR Could not create Appender [GelfAmqpAppender] of type [Gelf4Net.Appender.GelfAmqpAppender, Gelf4Net]. Reported error follows.
System.MissingFieldException: Champ introuvable : 'RabbitMQ.Client.ConnectionFactory.HostName'.
   à Gelf4Net.Appender.GelfAmqpAppender.InitializeConnectionFactory()
   à Gelf4Net.Appender.GelfAmqpAppender.ActivateOptions()
   à log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAppender(XmlElement appenderElement)
log4net:ERROR Appender named [GelfAmqpAppender] not found.

Could you help me ?

thank you very much

**Comment by jjchiw** [comment]
I think that if you only Build the project, what it's missing is the ILMerge with the `RabbitMQ.Client.dll`

Build the library with cake

`> build.ps1`

**Comment by raynaldgirard** [comment]
OK, I'll check that. By the way why are you GZip the message ?

Via mobile

Le 28 oct. 2017 ? 10:10, jjchiw <notifications@github.com<mailto:notifications@github.com>> a ?crit :


I think that if you only Build the project, what it's missing is the ILMerge with the RabbitMQ.Client.dll

Build the library with cake

> build.ps1

-

**Comment by jjchiw** [comment]
Graylog accepts both compressed/uncompressed

http://docs.graylog.org/en/2.3/pages/gelf.html

And I thought it was better to send the message compressed :)
