### ISSUE TITLE
Layout namespace should be Gelf4Net?

### ISSUE THREAD

**Issue by eoghan-kenny** [jjchiw/gelf4net#56]
The samples have Gelf4Net.AppenderName for or Gelf4Net.Core for Layout namespace, should be just Gelf4Net

**Comment by jjchiw** [comment]
Hi,

I don't understand the issue.....

Does the samples do not compile?

**Comment by eoghan-kenny** [comment]
Exactly sample did not compile, once laylout namespeace changed to Gelf4Net from Gelf4Net.Core all worked as expected

**Comment by jjchiw** [comment]
Fixed  8d490a8
