### ISSUE TITLE
Error loading configuration: Gelf4Net not found

### ISSUE THREAD

**Issue by Anthony-Breneliere** [jjchiw/gelf4net#69]
Appender configuration is incorrect since I update to Gelf4net 1.0.0.17.

With the configuration 

> <layout type="Gelf4Net.Layout.GelfLayout, Gelf4Net">

"Gelf4Net file is not found"

I had to update ther configuration to to:

> <layout type="Gelf4Net.Layout.GelfLayout">

Now it's OK but the documentation does not seem up-to-date.

**Comment by jjchiw** [comment]
Hi

So you figured out what was going on?

Where does the documentation is not up-to-date so I can fix it...

Thanks
