### ISSUE TITLE
Gelf4Net.UdpAppender dll is not signed

### ISSUE THREAD

**Issue by mathieuchateau** [jjchiw/gelf4net#72]
Dll is not signed, which makes loading it fails
"Assembly with a strong name is required. HRESULT : 0x80131044"
(translated from french).

I can sign it with my cert, but would have todo it again after each update.

Thanks in advance for your help

**Comment by jjchiw** [comment]
Hi

I'll look into this PR https://github.com/jjchiw/gelf4net/pull/24 and sign the assembly....

Have to check if the assemblies that gelf4net is using are signed if not I think I will not be able to sign it....

**Comment by mathieuchateau** [comment]
@jjchiw sorry to bother you, but I am deeply in need for using this dll to feed Graylog. Do you have any ETA on when you will merge this PR?
I tried to sign & strong name existing DLL, but dependency inside dll is not updated to use the strong name version :'(
I would like to avoid a fork here just to sign.

Thanks in advance,
BR
Mathieu

**Comment by jjchiw** [comment]
I'll sign it tonight gmt+1

**Comment by jjchiw** [comment]
Didn't find a time to do it tonight, I'll find time during the weekend

**Comment by mathieuchateau** [comment]
@jjchiw  ok thanks

**Comment by jjchiw** [comment]
I've signed all the assemblies and pushed to nuget also added an icon :)

https://www.nuget.org/packages/Gelf4Net.UdpAppender/1.0.0.18

**Comment by mathieuchateau** [comment]
@jjchiw thanks a lot dude !
