### ISSUE TITLE
gelf http Async DoAppend slow

### ISSUE THREAD

**Issue by mathieuchateau** [jjchiw/gelf4net#73]
Hello,

Using Gelf http Async, with DoAppend.
Even if it's meant to be async, submitting 50K loggingeventdata through doappend is quite slow, around 10 minutes.
I tried to play with number of threads and buffersize, but it doesn't look to change anything in speed.

Any clue ?

Thanks in advance,

**Comment by jjchiw** [comment]
Hi!..

I'll have to make some tests.....

I'll call @iwillspeak here, if he can give us some insights about the http async

**Comment by iwillspeak** [comment]
I have to admit we haven't used this library to push to Graylog for _quite some time_. Despite our best efforts it proved a challenge to prevent the publishing of logs to Graylog from having an impact on our service itself. We have switched to file logging + a log shipper instead. We use Beats to ship to Graylog and Fluentd to ship to SackDriver.

In general for high throughput the `GelfUdpAppender` seems to be a batter option. I've never used the HTTP appender for anything other than _the simplest of applications_. You have to deal with the potential of dropped log messages with that appender though.
