### ISSUE TITLE
Dependencies not added

### ISSUE THREAD

**Issue by FDonald** [jjchiw/gelf4net#74]
Hi,
We observe a strange behavior with gelf4Net dependencies.
We compile a standard Net Framework (V 4.52) application with Visual Studio 2013 and dependencies libraries are copied in bin directory. (Eg. Newtonsoft.Json.dll)

We compile same application with Visual Studio 2019 Msbuild (v 16.7) and dependencies libraries **not** are copied in bin directory. (Eg. Newtonsoft.Json.dll)

Inspecting package we found that .nuspec have this configuration:
<dependency id="Newtonsoft.Json" version="9.0.1" exclude="Build,Analyzers" />
So we suspect that new version of MsBuild v 16.7 does not copy necessary libraries in output folder and gelf appender not work!
Could you confirm this behavior, please? If so, we need add manually necessary dependency?
Thank you.

**Comment by jjchiw** [comment]
Hi!

I'm planning to upgrade library to .net5 and update all the nuget packages.... 

I'm not sure why the libraries are not copied... I'll look it through today and let you know

:)

**Comment by FDonald** [comment]
Sorry I forgot add nuspec configuration (downloaded form nuget): 

<dependency id="Newtonsoft.Json" version="9.0.1" **exclude="Build,Analyzers"** />

It seem that new compiler not add this type of dependecies.

**Comment by jjchiw** [comment]
I couldn't reproduce it....

I executed `./build.ps1` and I see the libraries copied
![image](https://user-images.githubusercontent.com/642319/108369881-5a8fc180-71fc-11eb-805b-43b0e2fd56a0.png)

I build it with

```
Microsoft (R) Build Engine version 16.9.0-preview-21078-04+968042dd0 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by FDonald** [comment]
Thanks @jjchiw.
Sorry, the behavior it's the same with all compiler, I will review proyect structure. As a difference, I add a reference to gel4Net directly. It is necessary or I could add Gelf4Net Core and Gel4$Net UdpAppender (or needed Appenders)?
Let me make a suggestion, please. When a dependency dll is missing, Why  not show Gelf4Net an error instead of  silently fail?

**Comment by jjchiw** [comment]
Ok
So it seems you are not using the Nuget Package with nuget all the dependencies are downloaded and should work....

So, if you want to reference the project you should reference `gelfnet` and it would pull all the dependencies....

I just pull the repo and `dotnet build` and this was the output

![image](https://user-images.githubusercontent.com/642319/108504855-d9e1cb80-72b6-11eb-847c-5c8b33472e4e.png)
