### ISSUE TITLE
In your readme the GELF Specification link are dead !

### ISSUE THREAD

**Issue by mcarbonneaux** [jjchiw/gelf4net#78]
In your readme the GELF Specification link are dead: https://github.com/Graylog2/graylog2-docs/wiki/GELF

now the documentation github project (`documentation` in place of `graylog2-doc`) as changed of place and now archived : https://github.com/Graylog2/documentation/blob/4.2/pages/gelf.rst

we can find it also on the official site: https://docs.graylog.org/v1/docs/gelf

**Comment by jjchiw** [comment]
Thanks, I have updated the link
