### ISSUE TITLE
where are params and their defaults documented

### ISSUE THREAD

**Issue by jasonrberk** [jjchiw/gelf4net#79]
what is the default value for `SendTimeStampAsString`?  My new Graylog instances is complaining

>GELF message <ccd88460-2570-11ed-8e61-0ee8466ead25> (received from <host:port>) has invalid "timestamp": 1661540192.05392  (type: STRING)

where are the the params documented?

**Comment by jjchiw** [comment]
Hi

The default value is `true`

https://github.com/jjchiw/gelf4net/blob/master/src/Gelf4Net.Core/Layout/GelfLayout.cs#L22

Here is how the transformation it's done
https://github.com/jjchiw/gelf4net/blob/master/src/Gelf4Net.Core/GelfMessage.cs#L70
