### ISSUE TITLE
Nothing gets added to graylog with log4net 3.x

### ISSUE THREAD

**Issue by AndyHore** [jjchiw/gelf4net#82]
log4net just release version 3.x and I updated to the latest NuGet packed and after wards our graylog entries stopped being added! I backed the log4net version down to 2.0.17 and they were back again.

**Comment by mindra** [comment]
Hello, have you had a chance to look at this issue? I'm experiencing the same behavior with the log4net 3.x version; no graylog entries are being added

**Comment by jjchiw** [comment]
No, sorry. 
Long weeks :/

But I'll try to find some hours during the week.

Thanks!

**Comment by jjchiw** [comment]
Updated

<img width="669" alt="image" src="https://github.com/user-attachments/assets/88fbf4af-9e65-42e2-82e7-c3c335a15766">

**Comment by AndyHore** [comment]
Thanks, works great.
