### ISSUE TITLE
With HttpAppender no entries are added in Graylog because the JSON payload contains line breaks

### ISSUE THREAD

**Issue by thomasvoneuw** [jjchiw/gelf4net#83]
I tried the gelf4net.HttpAppender in a .NET Framework 4.8.1 console application and no log entries were added to Graylog.
I figured out, that if I remove all linebreaks of the JSON string payload in GelfHttpAppender.cs method SendMessageAsync(string payload) before sending it with the httpClient, then it works fine.

`payload = payload.Replace("\r\n", "").Replace("\n", "");`

I was able to reproduce the same behavior with a simple Postman POST request. If the json payload has line breaks, the HTTP status code 202 is still returned, but no logs are shown in Graylog.

Do you have any idea what the issue is?
Could it be a misconfiguration of Graylog itself? Our Graylog version is: Graylog 5.2.5+7eaa89d on server (Eclipse Adoptium 17.0.10 on Linux 6.5.0-1017-azure)

Or is it a "bug" which needs to be fixed in the gelf4net library?
Any hints are appreciated!

Best regards and thanks
Tom

**Comment by jjchiw** [comment]
Hi

I'll try to look into it this weekend with that graylog version and will try to update to the new log4net https://github.com/jjchiw/gelf4net/issues/82
